version: '3'

services:
    sqlserver:
        image: mcr.microsoft.com/mssql/server:2019-latest
        container_name: sqlserver
        hostname: sqlserver
        restart: unless-stopped
        ports:
            - "1433:1433"
        volumes:
            - /mnt/sqlserver/data:/home/sqlserver/data
        environment:
            SA_PASSWORD: "@Victory10"
            ACCEPT_EULA: "Y"
            MSSQL_PID: "Developer"
            TZ: "America/Sao_Paulo"
